all:
  children:
    webserver:
      hosts:
        # ubuntu
        172.31.57.93:
          package_name_1: apache2
          package_name_2: php
        # centos
        # 172.31.48.132:
        #   package_name_1: httpd
        #   package_name_2: php
          
            
            