pipeline{
    agent none
    stages{
        stage('clone'){
            agent{
                label 'ubuntu-ansible'
            }
            steps{
                git url: 'https://github.com/tarunkumarpendem/Documentations.git',
                    branch: 'main'
            }
        }
        stage('ansible-playbook'){
            agent{
                label 'ubuntu-ansible'
            }
            steps{
                sh """
                      cd Ansible-Jenkins-Integration/
                      ansible -i hosts -m ping webserver
                      ansible-playbook -i hosts.yaml playbook.yaml
                    """ 
            }
        }
    }
}